# Generated by Django 6.0.2 on 2026-03-04 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duree', models.PositiveIntegerField(help_text='Durée en heures')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('progression', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('complete', 'Complété'), ('abandon', 'Abandonné')], default='en_cours', max_length=20)),
                ('employe', models.ForeignKey(limit_choices_to={'role': 'employe'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='certificats/')),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formations.inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('capacite', models.PositiveIntegerField()),
                ('salle', models.CharField(blank=True, max_length=100, null=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formations.formation')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formations.session'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('employe', 'session')},
        ),
    ]
